// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powerscale/internal/service (interfaces: MetricsRecorder,MeterCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/metrics_mocks.go -package=mocks github.com/dell/csm-metrics-powerscale/internal/service MetricsRecorder,MeterCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/dell/csm-metrics-powerscale/internal/service"
	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRecorder is a mock of MetricsRecorder interface.
type MockMetricsRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRecorderMockRecorder
	isgomock struct{}
}

// MockMetricsRecorderMockRecorder is the mock recorder for MockMetricsRecorder.
type MockMetricsRecorderMockRecorder struct {
	mock *MockMetricsRecorder
}

// NewMockMetricsRecorder creates a new mock instance.
func NewMockMetricsRecorder(ctrl *gomock.Controller) *MockMetricsRecorder {
	mock := &MockMetricsRecorder{ctrl: ctrl}
	mock.recorder = &MockMetricsRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRecorder) EXPECT() *MockMetricsRecorderMockRecorder {
	return m.recorder
}

// RecordClusterCapacityStatsMetrics mocks base method.
func (m *MockMetricsRecorder) RecordClusterCapacityStatsMetrics(ctx context.Context, arg1 *service.ClusterCapacityStatsMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClusterCapacityStatsMetrics", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClusterCapacityStatsMetrics indicates an expected call of RecordClusterCapacityStatsMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordClusterCapacityStatsMetrics(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClusterCapacityStatsMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordClusterCapacityStatsMetrics), ctx, arg1)
}

// RecordClusterPerformanceStatsMetrics mocks base method.
func (m *MockMetricsRecorder) RecordClusterPerformanceStatsMetrics(ctx context.Context, arg1 *service.ClusterPerformanceStatsMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClusterPerformanceStatsMetrics", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClusterPerformanceStatsMetrics indicates an expected call of RecordClusterPerformanceStatsMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordClusterPerformanceStatsMetrics(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClusterPerformanceStatsMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordClusterPerformanceStatsMetrics), ctx, arg1)
}

// RecordClusterQuota mocks base method.
func (m *MockMetricsRecorder) RecordClusterQuota(ctx context.Context, meta any, arg2 *service.ClusterQuotaRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClusterQuota", ctx, meta, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClusterQuota indicates an expected call of RecordClusterQuota.
func (mr *MockMetricsRecorderMockRecorder) RecordClusterQuota(ctx, meta, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClusterQuota", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordClusterQuota), ctx, meta, arg2)
}

// RecordTopologyMetrics mocks base method.
func (m *MockMetricsRecorder) RecordTopologyMetrics(ctx context.Context, meta any, arg2 *service.TopologyMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordTopologyMetrics", ctx, meta, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordTopologyMetrics indicates an expected call of RecordTopologyMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordTopologyMetrics(ctx, meta, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTopologyMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordTopologyMetrics), ctx, meta, arg2)
}

// RecordVolumeQuota mocks base method.
func (m *MockMetricsRecorder) RecordVolumeQuota(ctx context.Context, meta any, arg2 *service.VolumeQuotaMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordVolumeQuota", ctx, meta, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordVolumeQuota indicates an expected call of RecordVolumeQuota.
func (mr *MockMetricsRecorderMockRecorder) RecordVolumeQuota(ctx, meta, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordVolumeQuota", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordVolumeQuota), ctx, meta, arg2)
}

// MockMeterCreator is a mock of MeterCreator interface.
type MockMeterCreator struct {
	ctrl     *gomock.Controller
	recorder *MockMeterCreatorMockRecorder
	isgomock struct{}
}

// MockMeterCreatorMockRecorder is the mock recorder for MockMeterCreator.
type MockMeterCreatorMockRecorder struct {
	mock *MockMeterCreator
}

// NewMockMeterCreator creates a new mock instance.
func NewMockMeterCreator(ctrl *gomock.Controller) *MockMeterCreator {
	mock := &MockMeterCreator{ctrl: ctrl}
	mock.recorder = &MockMeterCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterCreator) EXPECT() *MockMeterCreatorMockRecorder {
	return m.recorder
}

// MeterProvider mocks base method.
func (m *MockMeterCreator) MeterProvider() (metric.Meter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeterProvider")
	ret0, _ := ret[0].(metric.Meter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeterProvider indicates an expected call of MeterProvider.
func (mr *MockMeterCreatorMockRecorder) MeterProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeterProvider", reflect.TypeOf((*MockMeterCreator)(nil).MeterProvider))
}
