// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powerscale/internal/service (interfaces: PowerScaleClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/powerscale_client_mocks.go -package=mocks github.com/dell/csm-metrics-powerscale/internal/service PowerScaleClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gopowerscale "github.com/dell/gopowerscale"
	gomock "go.uber.org/mock/gomock"
)

// MockPowerScaleClient is a mock of PowerScaleClient interface.
type MockPowerScaleClient struct {
	ctrl     *gomock.Controller
	recorder *MockPowerScaleClientMockRecorder
	isgomock struct{}
}

// MockPowerScaleClientMockRecorder is the mock recorder for MockPowerScaleClient.
type MockPowerScaleClientMockRecorder struct {
	mock *MockPowerScaleClient
}

// NewMockPowerScaleClient creates a new mock instance.
func NewMockPowerScaleClient(ctrl *gomock.Controller) *MockPowerScaleClient {
	mock := &MockPowerScaleClient{ctrl: ctrl}
	mock.recorder = &MockPowerScaleClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerScaleClient) EXPECT() *MockPowerScaleClientMockRecorder {
	return m.recorder
}

// GetAllQuotas mocks base method.
func (m *MockPowerScaleClient) GetAllQuotas(ctx context.Context) (gopowerscale.QuotaList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuotas", ctx)
	ret0, _ := ret[0].(gopowerscale.QuotaList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuotas indicates an expected call of GetAllQuotas.
func (mr *MockPowerScaleClientMockRecorder) GetAllQuotas(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuotas", reflect.TypeOf((*MockPowerScaleClient)(nil).GetAllQuotas), ctx)
}

// GetFloatStatistics mocks base method.
func (m *MockPowerScaleClient) GetFloatStatistics(ctx context.Context, keys []string) (gopowerscale.FloatStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloatStatistics", ctx, keys)
	ret0, _ := ret[0].(gopowerscale.FloatStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloatStatistics indicates an expected call of GetFloatStatistics.
func (mr *MockPowerScaleClientMockRecorder) GetFloatStatistics(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloatStatistics", reflect.TypeOf((*MockPowerScaleClient)(nil).GetFloatStatistics), ctx, keys)
}
