// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powerscale/internal/service (interfaces: StorageClassFinder)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/storage/v1"
)

// MockStorageClassFinder is a mock of StorageClassFinder interface.
type MockStorageClassFinder struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClassFinderMockRecorder
}

// MockStorageClassFinderMockRecorder is the mock recorder for MockStorageClassFinder.
type MockStorageClassFinderMockRecorder struct {
	mock *MockStorageClassFinder
}

// NewMockStorageClassFinder creates a new mock instance.
func NewMockStorageClassFinder(ctrl *gomock.Controller) *MockStorageClassFinder {
	mock := &MockStorageClassFinder{ctrl: ctrl}
	mock.recorder = &MockStorageClassFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClassFinder) EXPECT() *MockStorageClassFinderMockRecorder {
	return m.recorder
}

// GetStorageClasses mocks base method.
func (m *MockStorageClassFinder) GetStorageClasses(arg0 context.Context) ([]v1.StorageClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageClasses", arg0)
	ret0, _ := ret[0].([]v1.StorageClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageClasses indicates an expected call of GetStorageClasses.
func (mr *MockStorageClassFinderMockRecorder) GetStorageClasses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageClasses", reflect.TypeOf((*MockStorageClassFinder)(nil).GetStorageClasses), arg0)
}
